#!/bin/sh

if ! command -v bash >/dev/null 2>&1; then
    echo "Error: bash is required but not installed." >&2

    if [ "$(id -u)" -eq 0 ]; then
        echo -n " install bash using your package manager? (y/n)."
       command read REPLY
        while [ "$REPLY" != "y" ] && [ "$REPLY" != "n"  ]; do
           echo  -n "invalid option : (y/n) "
           command read REPLY
        done
        if [ "$REPLY" = "n"   ];then 
            sleep 1
            echo '[+] exiting ...'
            exit 0 
         fi
         if [ "$REPLY" = "y"  ]; then 
             sleep 2
          echo "good boy:..."  

    
        exit 0
        fi

    else
        echo "Please install bash as root and rerun this script."
        echo "For example:"
        echo "  sudo apt install bash"
        echo "or log in as root and install it."
    fi

    exit 1
fi

 exec bash ./serversetup
