#!/usr/bin/env sh 
#FreeBSD dependencies:
for cmd in gcc11 autotools pkgconf cmake ninja libunwind pcre2 openssl lua51 opendap-client sqlite3 libxml2 ;do

command -v "$cmd" >dev/null 2>&1 || pkg install -y "$cmd"
done 
#Configure

#To help autotools find libraries and headers:
CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib 
#=========================================================================
#---this script is just a copy of the readme.freebsd in lightppd repo
#==========================================================================
#- compiler:
 # pkg install gcc11
 # or
#  pkg install llvm13
# autotools + pkgconf (for builds from svn/git)
  #pkg install autotools pkgconf
#-# pkgconf might be needed to find libs in build from tarball too:
  #pkg install pkgconf
#- building with cmake + ninja instead of autotools:
 # pkg install cmake ninja
#- stack traces on asserts:
 # pkg install libunwind
#- PCRE (mod_rewrite, mod_redirect, config conditionals, ...)
 # pkg install pcre2
#- TLS support (and mod_auth {SHA1} support)
 # pkg install libressl
  #or
 # pkg install openssl
#- Lua 5.1, 5.2, 5.3, or 5.4 (mod_magnet)
 # pkg install lua51 # (or lua52 or lua53 or lua54)
#- LDAP (mod_auth feature)
 # pkg install openldap-client
#- SQLite3 (mod_webdav WebDAV properties and locking)
  #pkg install sqlite3
#- XML (mod_webdav WebDAV properties and locking)
 # pkg install libxml2

#Configure:

